---
title: "Scenario Summary Calculations"
author: "Dorit Stein"
date: "1/17/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(stringr)

```

# 0. load data

```{r load data}

# Oct 5 output from 2 runs [test]

#s1 <- readRDS("3 Output/s1-Oct5.rds")
s1 <- readRDS("3 Output/s1-rnorm-clean-3.rds") %>%
  unnest(s1_output)

#s2 <- readRDS("3 Output/s2-3.rds")
s2  <- readRDS("3 Output/s2-rnorm-clean.rds") %>%
  unnest(s2_output)

```

# 1. Summary calculations from scenario 1 + 2 output

```{r clean scenarios and summary calculations}

# baseline to merge in and get relative change in CVD risk
baseline <- readRDS("3 Output/baseline-calcs.rds")

baseline1 <- baseline %>%
  rename(country = Country)

# scenario 1

s1_calcs <- s1 |>
  mutate(mean = case_when(name == "mean_rel_change_s1_rnorm" ~ mean*100, # relative (%) change in CVD risk
                          name == "mean_cvd_risk_s1_rnorm" ~ mean*100, # mean CVD risk (%)
                          name == "mean_risk_d_s1_rnorm" ~ mean*1000,  # mean difference in CVD cases per 1,000 hypertensives
                          TRUE ~ NA_real_),
         lower = case_when(name == "mean_rel_change_s1_rnorm" ~ lower*100,
                           name == "mean_cvd_risk_s1_rnorm" ~ lower*100,
                           name == "mean_risk_d_s1_rnorm" ~ lower*1000,
                           TRUE ~ NA_real_),
         upper = case_when(name == "mean_rel_change_s1_rnorm" ~ upper*100,
                           name == "mean_cvd_risk_s1_rnorm" ~ upper*100,
                           name == "mean_risk_d_s1_rnorm" ~ upper*1000,
                           TRUE ~ NA_real_)) |>
  mutate(scenario = "Scenario 1: Diagnosis",
         measure = case_when(name == "mean_rel_change_s1_rnorm" ~ "mean_rel_c",
                             name == "mean_cvd_risk_s1_rnorm" ~ "mean_cvd_risk",
                             name == "mean_risk_d_s1_rnorm" ~ "mean_risk_d"),
         name = case_when(name == "mean_rel_change_s1_rnorm" ~ "Mean Relative (%) Change in CVD Risk",
                          name == "mean_cvd_risk_s1_rnorm" ~ "Mean CVD Risk (%)",
                          name == "mean_risk_d_s1_rnorm" ~ "Mean Difference in CVD Cases per 1,000 Hypertensives")) 

# scenario 2
  
  s2_calcs <- s2 |>
  mutate(mean = case_when(name == "mean_rel_change_s2_rnorm" ~ mean*100, # relative (%) change in CVD risk
                          name == "mean_cvd_risk_s2_rnorm" ~ mean*100, # mean CVD risk (%)
                          name == "mean_risk_d_s2_rnorm" ~ mean*1000,  # mean difference in CVD cases per 1,000 hypertensives
                          TRUE ~ NA_real_),
         lower = case_when(name == "mean_rel_change_s2_rnorm" ~ lower*100,
                           name == "mean_cvd_risk_s2_rnorm" ~ lower*100,
                           name == "mean_risk_d_s2_rnorm" ~ lower*1000,
                           TRUE ~ NA_real_),
         upper = case_when(name == "mean_rel_change_s2_rnorm" ~ upper*100,
                           name == "mean_cvd_risk_s2_rnorm" ~ upper*100,
                           name == "mean_risk_d_s2_rnorm" ~ upper*1000,
                           TRUE ~ NA_real_)) |>
  mutate(scenario = "Scenario 2: Treatment",
         measure = case_when(name == "mean_rel_change_s2_rnorm" ~ "mean_rel_c",
                             name == "mean_cvd_risk_s2_rnorm" ~ "mean_cvd_risk",
                             name == "mean_risk_d_s2_rnorm" ~ "mean_risk_d"),
         name = case_when(name == "mean_rel_change_s2_rnorm" ~ "Mean Relative (%) Change in CVD Risk",
                          name == "mean_cvd_risk_s2_rnorm" ~ "Mean CVD Risk (%)",
                          name == "mean_risk_d_s2_rnorm" ~ "Mean Difference in CVD Cases per 1,000 Hypertensives")) 
 
#baseline
baseline2 <- baseline1 %>%
  mutate(scenario = "Baseline",
         measure = "mean_cvd_risk",
         name = "Mean CVD Risk (%)") %>%
  mutate(mean = mean_cvd_risk_b*100,
         lower = mean_cvd_risk_b_low*100,
         upper = mean_cvd_risk_b_upp*100) %>%
  select(-mean_cvd_risk_b, -mean_cvd_risk_b_low, -mean_cvd_risk_b_upp)

# save scenario results separately
saveRDS(s1_calcs, "3 Output/s1_calcs.rds")
saveRDS(s2_calcs, "3 Output/s2_calcs.rds")
saveRDS(baseline2, "3 Output/baseline2.rds")
#saveRDS(s1_calcs_rel, "3 Output/s1_calcs_rel.rds")
#saveRDS(s2_calcs_rel, "3 Output/s2_calcs_rel.rds")

#test<- readRDS("3 Output/s1_calcs.rds")

###bind results from scenario 1, scenario 2, and baseline
scenario_calcs <- rbind(s1_calcs, s2_calcs)
scenario_calcs_baseline <- rbind(scenario_calcs, baseline2)

# save
saveRDS(scenario_calcs, file = "3 Output/all-scenarios.rds")
saveRDS(scenario_calcs_baseline, file = "3 Output/all-scenarios-baseline.rds")

```






# Calc of # of cases per quintile
-Take quintile populations (population/5) and multiply by quintile-specific HTN prevalence--> # of HTNs in each quintile
-Then take # of htns in each quintile and apply absolute case difference (ie 20 less per 1,000) to get total cases averted among hypertensives

```{r}
# from 3 results tables script
abs <- readRDS("3 Output/abs.rds")
#saveRDS(rel, "3 Output/rel.rds")

htn_quintile <- readRDS(file ="3 Output/htn-quintile.rds")
pop_quintile <- readRDS(file = "3 Output/pop_quint_forty_plus.rds") # from "A Population Totals.RMD" script

data <- left_join(htn_quintile, pop_quintile)

htn_n <- data %>%
  mutate(number_htn = round(mean_htn*quintile_pop,0)) %>%
  rename(country = Country)

htn_n$wealth_quintile <- factor(htn_n$wealth_quintile,
                                     levels = c("1", "2", "3", "4", "5"),
                                      labels= c("Q1", "Q2", "Q3", "Q4", "Q5"))

htn_abs <- htn_n %>%
  left_join(abs) %>%
  mutate(per_diff = mean/1000,
         abs_case_diff = number_htn*per_diff) 

# no weights (i.e. weighted by population/number of htns - bigger countries contribute more to the numbers)
abs_diff <- htn_abs %>%
  group_by(wealth_quintile, scenario) %>%
  summarize(abs_case_diff = sum(abs_case_diff, na.rm = T)) %>%
  ungroup() %>%
  group_by(scenario) %>%
  mutate(sum = sum(abs_case_diff),
         prop = abs_case_diff/sum)

# proportion of cases in bottom quintiles BY COUNTRY - take average (like equal weighting?)
abs_diff <- htn_abs %>%
  group_by(country, wealth_quintile, scenario) %>%
  mutate(abs_case_diff = sum(abs_case_diff, na.rm = T),
            n_htn = sum(number_htn)) %>%
  ungroup() %>%
  group_by(country, scenario) %>%
  mutate(sum = sum(abs_case_diff),
         prop = abs_case_diff/sum,
         sum_htn = sum(n_htn),
         prop_htn = n_htn/sum_htn) 

# avg by scenario
abs_diff_avg_overall <- abs_diff %>%
  group_by(wealth_quintile, scenario) %>%
 summarize(avg_diff = mean(prop),
            avg_htn_prop = mean(prop_htn)) 

write.csv(abs_diff_avg_overall, "3 Output/avg-prop-cases-averted.csv")

# long
abs_diff_avg <- abs_diff %>%
  group_by(wealth_quintile, scenario) %>%
 summarize(avg_diff = mean(prop),
            avg_htn_prop = mean(prop_htn)) %>%
  pivot_longer(cols = avg_diff:avg_htn_prop)

# avg by GDP
abs_diff_avg <- abs_diff %>%
  group_by(wealth_quintile, scenario, countryGDPclass) %>%
 summarize(avg_diff = mean(prop),
            avg_htn_prop = mean(prop_htn)) %>%
  pivot_longer(cols = avg_diff:avg_htn_prop)

# total abs cases averted
abs_diff_total <- htn_abs %>%
  group_by(scenario) %>%
  mutate(sum_scenario = sum(abs_case_diff))

abs_diff_total2<- abs_diff_total %>%
  group_by(scenario, wealth_quintile) %>% 
  summarize(abs_case_diff = round(sum(abs_case_diff, na.rm = T),0),
            prop_cases = round((abs_case_diff/sum_scenario), 3)) %>%
  unique()

write.csv(abs_diff_total2, "3 Output/total-cases-averted.csv")

abs_diff_total_lmic <- htn_abs %>%
  group_by(scenario, countryGDPclass) %>%
  mutate(sum_scenario = sum(abs_case_diff))

abs_diff_total3<- abs_diff_total_lmic %>%
  group_by(scenario, wealth_quintile, countryGDPclass) %>% 
  summarize(abs_case_diff = round(sum(abs_case_diff, na.rm = T),0),
            prop_cases = round((abs_case_diff/sum_scenario), 3)) %>%
  unique()


```


